### ISSUE TITLE
Add a Military Tools Button to the Analysis Ribbon

### ISSUE THREAD

**Issue by topowright** [Esri/military-tools-desktop-addins#66] opened 2018-08-30 21:51 UTC
Currently we have a python package and conda package for Military Tools. We give users the ability to install these tools as a system tool; however, we would like to create a button the analysis ribbon that gives our users the ability to find these tools in a custom button dialog drop down menu. 

#### Current State
The gp tools live in the following repo: 
https://github.com/Esri/military-tools-geoprocessing-toolbox

Crime Analysis addin  is a good example of already doing this: 
https://solutions.arcgis.com/local-government/help/crime-analysis/
![image](https://user-images.githubusercontent.com/5322669/47383649-fe631400-d6b9-11e8-9fa8-45fb90122f77.png)
_when you hover over the button there is a tooltip with short description. Once you click the button you are presented with a list of the gp tools grouped by toolset in a gray header. The toolset does not need a description or icon, just name. Each tool has a name, icon, and short description. Icons are [here](https://github.com/Esri/military-tools-desktop-addins/issues/66#issuecomment-427185953). Toolsets/tools/descriptions provided [here](https://github.com/Esri/military-tools-desktop-addins/issues/66#issuecomment-432375986)_

This (Crime Analysis) must be downloaded from the Solutions Deployment Tool: 
https://solutions.arcgis.com/shared/help/deployment-tool/

These tools are not accessible in a way that takes advantage of the ArcGIS Pro custom ribbons
### Expected Behavior

- [ ] Add a custom button to the analysis ribbon
- [ ] Store the python package or conda package in a local directory so that the ribbon can find the tools (Possibly the assembly cache)
- [ ] If the user has the conda package for Military Tools installed allow the button to work using the Military Tools that are access like system tools
- [ ] Add the tools into their custom sections based on the tools box
- conversion
- grg
- visibility
- distance and direction
- [ ] Add custom icons for each tool
- [ ] Add description for each tool

### Your Environment
This will only be done for ArcGIS Pro

**Comment by topowright** [comment] 2018-10-04 22:10
Here are the icons for the drop down menu. 
[PNGs.zip](https://github.com/Esri/military-tools-desktop-addins/files/2448276/PNGs.zip)

**Comment by dfoll** [comment] 2018-10-23 18:57
|Toolset |Tool|Description|
| ----- | ----- | ----- | 
|Conversion| | |

**Comment by dfoll** [comment] 2018-11-05 13:13
@CTLocalGovTeam has provided their code [here](https://github.com/Esri/military-tools-desktop-addins/tree/cybertech-dev). The summary of the problem is that they have provided a working solution for Pro 2.2 but it fails in Pro 2.1. They have asked that we reach out to core to see if we can get any assistance for why this might be.

**Comment by dfoll** [comment] 2018-11-05 13:54
I tried doing a build so we could start investigating this and maybe get to the bottom of it. [This is what happens](http://soljenkinsprod:8080/blue/organizations/jenkins/MT_Pipeline/detail/MT_Pipeline/124/pipeline).

Note that I am also building this from my own [test branch](https://github.com/ArcGIS/solutions-defense/tree/df-build-to-test-CT-issue-66) in solutions-defense that I am trying to use to test this before merging.

**Comment by saip** [comment] 2018-11-05 17:56
@csmoore Thanks for sharing the info.
@dfoll The xmls were auto ignored by the Git source control. We have added them back now to **cybertech-dev** branch.

We have not yet discussed regarding the inclusion of the script files at root folder directly from the repo. I believe that would be good, as that is how we are doing this for other addins of military tools

**Comment by saip** [comment] 2018-11-05 17:57
b

**Comment by dfoll** [comment] 2018-11-05 18:01
[build_errors.txt](https://github.com/Esri/military-tools-desktop-addins/files/2549987/build_errors.txt)

**Comment by csmoore** [comment] 2018-11-05 21:31
@saip -working with @dfoll - we got a little further in the build.

Fixed these issues:

1. Jenkins issue with renaming repo: https://github.com/Esri/military-symbology
2. Build issue with C# 6 syntax https://github.com/Esri/military-tools-desktop-addins/pull/79

But there seems to be a remaining issue in script: 

1. Build script is failing on this line: https://github.com/Esri/military-tools-desktop-addins/blob/cybertech-dev/tools/src/recipe/ca-conda-build.bat#L5 - because it cannot find `conda-build` in folder: `C:\Program Files\ArcGIS\Pro\bin\Python\Scripts` 
    a. Is this something that has been added to the default Pro configuration and can we get a copy?

**Comment by csmoore** [comment] 2018-11-06 13:28
@dfoll @saip - got a little further by installing the `conda-build` dependency [mentioned above](https://github.com/Esri/military-tools-desktop-addins/issues/66#issuecomment-436042873) with steps:

1. Go to: C:\Program Files\ArcGIS\Pro\bin\Python\Scripts
2. Run proenv.bat **As Administrator**
3. activate root
4. conda install conda-build

But now getting an error on step: `python: can't open file 'setup.py': [Errno 2] No such file or directory` - [Error Log - CondaError.txt](https://github.com/Esri/military-tools-desktop-addins/files/2553297/CondaError.txt)

**Comment by dfoll** [comment] 2018-11-15 23:39
@saip we have finished reorganizing the files in https://github.com/Esri/military-tools-geoprocessing-toolbox you can now update your code to pull from here for the .pyt. @csmoore also added PR #81 to add the additional repo to clone.

**Comment by dfoll** [comment] 2018-11-16 15:12
#### Info for the team
This is a conversation @saip  and I had. I have not built from his branch yet, but you can see the functionality described by looking at crime analysis and ready to use tools. I have told @saip that we do not need to maintain highlighting as crime analysis does, as ready to use tools does not do it, and I do not understand what value it would have. please respond here if you disagree

[‎11/‎16/‎2018 6:31 AM]  Sai Phaneendra:  
Ok, while testing this morning I came across a behavior with military tools button which I want to confirm
You can see the behavior I am about to talk with Crime analysis button and ready to use tools button in analysis tab
[‎11/‎16/‎2018 6:32 AM]  Sai Phaneendra:  
Do we need to keep selected item highlighted in the list of tools in the MT gallery dropdown
Crime analysis does and Ready to use tools does not
[‎11/‎16/‎2018 6:34 AM]  Sai Phaneendra:  
If we don't want to maintain selection, it's fine.
If we want selection to be maintained, then we see a bug with crime analysis
[‎11/‎16/‎2018 6:35 AM]  Sai Phaneendra:  
The selection stays on even a tool from another toolbox is selected from analysis tab
[‎11/‎16/‎2018 6:35 AM]  
you're talking about ...
1. open the button
2. click a tool
3. gp tool opens
4. click crime analysis again
5. button expands
6. previous tool is still highlighted
???
[‎11/‎16/‎2018 6:35 AM]  Sai Phaneendra:  
Yes
[‎11/‎16/‎2018 6:36 AM]  Sai Phaneendra:  
But, even after selecting a tool from say ready to use tools is selected
[‎11/‎16/‎2018 6:36 AM]  Sai Phaneendra:  
or we close the geoprocessing dock pane
[‎11/‎16/‎2018 6:36 AM]  Sai Phaneendra:  
it is still highlighted
I tried finding an event that would let me know the tools changed event or something similar but I could not find
[‎11/‎16/‎2018 6:37 AM]  
yes, i think i see what you are talking about
[‎11/‎16/‎2018 6:37 AM]  
i think it does not need to stay highlighted
[‎11/‎16/‎2018 6:38 AM]  
i will ask ryan what his logic is for that, but right now, i don't see what value it adds
[‎11/‎16/‎2018 6:38 AM]  Sai Phaneendra:  
It would never be highlighted, same as the behavior as ready to use tools
[‎11/‎16/‎2018 6:38 AM]  Sai Phaneendra:  
Is this ok, if I deliver what I mentioned in the above statement
[‎11/‎16/‎2018 6:38 AM]  Sai Phaneendra:  
?
[‎11/‎16/‎2018 6:38 AM]  
yes, deliver that
if i find that it needs to be highlighted i will get back to you and let you know
[‎11/‎16/‎2018 6:39 AM]  
thanks

**Comment by dfoll** [comment] 2018-11-29 13:14
This was merged. Testing happened before merge from CT-branch. We saw some symbology issues ([391](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/391) and were uncovered during testing but not something that was introduced with this branch  #85). Would like to see this tested one more time from the version that builds from dev (167 or later)

**Comment by dfoll** [comment] 2018-12-13 17:43
@sap what would the level of effort be to move the Military Tools button to the Tools section of the Analysis ribbon before we do our final QC-Verify and close this out?

**Comment by BobBooth** [comment] 2018-12-13 17:50
In build 170, the **Table to 2 Point Line** tool has missing spaces in the name (3.3.0.170). It says "TableTo 2 PointLine" 
The other tool names and descriptions look good.

**Comment by saip** [comment] 2018-12-13 18:08
@dfoll @BobBooth Corrected the tool name **Table To 2-Point Line** and moved the Military Tools button to the Tools section of the Analysis ribbon.

Changes are included in PR #87

**Comment by BobBooth** [comment] 2018-12-13 19:31
Added to the What's new section for this release in the Resources tab:
"The Military Tools geoprocessing tools are available on the ArcGIS Pro Analysis ribbon, from the Military Tools button."

Added to the Get Started page in the Install the toolbox for ArcGIS Pro section, an Esri StepInfo tag after step 5
Note: When you install the Military Tools for ArcGIS add-in for ArcGIS Pro, you get access to these geoprocessing tools from the Military Tools button on the Analysis ribbon. 

Added to Defense What's New page:
Added Military Tools button to ArcGIS Pro Analysis ribbon to provide access to the Military Tools geoprocessing tools. (PR 7336 - @dfoll  please review and merge)

**Comment by BobBooth** [comment] 2018-12-13 19:59
With the latest build, I confirm that the Military Tools button has been moved into the general "Tools" section of the Analysis ribbon, beside Network Analysis, Geostatistical Wizard, Business Analyst.
![image](https://user-images.githubusercontent.com/3801392/49964042-8d84ef00-fee7-11e8-8016-fab45913cd0b.png)
and
Table To 2-Point Line tool name has been fixed.
![image](https://user-images.githubusercontent.com/3801392/49964119-b4dbbc00-fee7-11e8-99d4-55bd0628c210.png)

**Comment by BobBooth** [comment] 2018-12-13 20:37
Ran each of the tools once, with our test dataset, they all produced correct results.

**Comment by BobBooth** [comment] 2018-12-14 17:43
Tested build 172 (from Dev) on Pro 2.1, no issues, except known issue about GRG from Point not running unless in Web Mercator (not related to this issue) and symbology of input points being generic blue "pin" symbols for most tools.
![image](https://user-images.githubusercontent.com/3801392/50018584-cf706c80-ff9d-11e8-8bac-72d8f7bce6cb.png)

**Comment by BobBooth** [comment] 2018-12-14 19:53
Added issue https://github.com/Esri/military-tools-desktop-addins/issues/88
@dfoll @lfunkhouser

**Comment by lfunkhouser** [comment] 2018-12-19 02:12
Input symbology is not as expected and a bug (logged as issue #88 ) needs to be addressed in order to be complete. Symbology of input points should not be generic blue "pin" symbols. @saip please work with @dfoll if further clarification is needed.  
FYI: @CTLocalGovTeam

**Comment by dfoll** [comment] 2019-01-18 18:30
#88 and #85 have both been moved to done, [391](https://github.com/Esri/military-tools-geoprocessing-toolbox/issues/391) is a gp issue, not an issue with the work to add the button. @lfunkhouser  can this be moved to done?

**Closed** 2019-01-18 21:08 UTC
Labels: A-feature, CT-Fixed, CyberTech, E-verified, V -  Pro 2.1, V - MT 3.3
