### ISSUE TITLE
BUG-000127566  The Number Features tool (Military Tools for ArcGIS) draws non-numbered points instead of numbered polygons.

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/military-tools-desktop-addins#126] opened 2020-01-22 15:25 UTC
<div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/SFTriage?sfid=BUG-000127566">BUG-000127566</a></span><br/>
<span><b>Salesforce Submitter:</b> Nikolas Dingus</span><br/>
<span><b>Salesforce Submit Date:</b> 12/23/2019 10:53 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> ...\sf_filestore\PRD\Attachments\Defects\BUG-000127566</span><br/>

### Synopsis:
The Number Features tool (Military Tools for ArcGIS) draws non-numbered points instead of numbered polygons.

### Steps to Repro:

1. Install the Military Tools for ArcGIS add-in 3.5 or 3.6
2. Create a new project in ArcGIS Pro and add a new map
3. Create an Area of Interest (AOI) polygon

- AOI feature in attached file geodatabase (02461033.zip)

4. Create a feature class to be numbered

- CompoundBuildings in attached file geodatabase

5. In the geoprocessing pane, search for the Number Features tool and input the following parameters

- Input Area to Number: AOI
- Features to Number: CompundBuildings
- Field to Number: leave blank
- Output Numbered Features: give the feature the desired name

6. Add the output to the map and notice the symbology. In Military Tools 3.4 and lower, the output is militarytools_old.png while the current output is militarytools_new.png

 
Note: Even though the geometry for the output of step 5 is listed as a polygon, if you select the layer and try to change the symbology, point symbols will appear

<span><b>Work Around:</b> <p>Set the primary symbology to anything other than the default &#39;<b>Single Symbol</b>&#39; and change it back to single symbol.</p></span><br/>

<span><b>Product:</b> ArcGIS Pro</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 2.4.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by lfunkhouser** [comment] 2020-02-19 22:19
This issue has been moved to devtopia, but keeping it open here until it has been addressed. We will close out when it is fixed/closed out in devtopia.

**Comment by dfoll** [comment] 2020-04-15 15:26
This is fixed in the next release of Pro (2.6). The tool is included in Pro 2.6. 

 The tool went through a pretty heavy internal redesign. The tool now accepts a polygon input and has a derived output. The numbers are added to this derived output instead of creating a new point output.  

In short, two fixes in the new design to help this tool. 1.) Since the output is derived, when polygon is input, polygon is output, instead of generating points to number a polygon fc. 2. Confirmed the numbering of the derived polygon feature class.

**Closed as completed** 2020-04-15 15:29 UTC
Labels: E-verified, Support
